/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/account/invitations/{business_id}/{client_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Client Account */
        post: operations["activate_client_account_v1_account_invitations__business_id___client_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/client/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Client Session */
        get: operations["client_session_v1_client_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Appointment */
        post: operations["create_appointment_v1_owner_businesses__business_id__appointments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/appointments/{appointment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Owner Appointment */
        get: operations["get_owner_appointment_v1_owner_businesses__business_id__appointments__appointment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Appointment */
        patch: operations["edit_appointment_v1_owner_businesses__business_id__appointments__appointment_id__patch"];
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/appointments/{appointment_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_v1_owner_businesses__business_id__appointments__appointment_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Block */
        post: operations["create_block_v1_owner_businesses__business_id__blocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/blocks/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Owner Block */
        get: operations["get_owner_block_v1_owner_businesses__business_id__blocks__block_id__get"];
        /** Move Block */
        put: operations["move_block_v1_owner_businesses__business_id__blocks__block_id__put"];
        post?: never;
        /** Remove Block */
        delete: operations["remove_block_v1_owner_businesses__business_id__blocks__block_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/booking-invitations/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Manual Invitations */
        get: operations["preview_manual_invitations_v1_owner_businesses__business_id__booking_invitations_manual_get"];
        put?: never;
        /** Send Manual Invitations */
        post: operations["send_manual_invitations_v1_owner_businesses__business_id__booking_invitations_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/booking-outreach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking Outreach */
        get: operations["get_booking_outreach_v1_owner_businesses__business_id__booking_outreach_get"];
        /** Edit Booking Outreach */
        put: operations["edit_booking_outreach_v1_owner_businesses__business_id__booking_outreach_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owner Calendar */
        get: operations["owner_calendar_v1_owner_businesses__business_id__calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_v1_owner_businesses__business_id__clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_v1_owner_businesses__business_id__clients__client_id__get"];
        /** Save Client */
        put: operations["save_client_v1_owner_businesses__business_id__clients__client_id__put"];
        post?: never;
        /** Erase Client */
        delete: operations["erase_client_v1_owner_businesses__business_id__clients__client_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/clients/{client_id}/account-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Client Account Status */
        get: operations["client_account_status_v1_owner_businesses__business_id__clients__client_id__account_invitation_get"];
        put?: never;
        /** Invite Client Account */
        post: operations["invite_client_account_v1_owner_businesses__business_id__clients__client_id__account_invitation_post"];
        /** Revoke Client Account */
        delete: operations["revoke_client_account_v1_owner_businesses__business_id__clients__client_id__account_invitation_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/clients/{client_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Client Notes */
        get: operations["list_client_notes_v1_owner_businesses__business_id__clients__client_id__notes_get"];
        put?: never;
        /** Create Client Note */
        post: operations["create_client_note_v1_owner_businesses__business_id__clients__client_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/clients/{client_id}/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Client Note */
        delete: operations["delete_client_note_v1_owner_businesses__business_id__clients__client_id__notes__note_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/clients/{client_id}/notes/{note_id}/legal-hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Client Note Hold */
        patch: operations["change_client_note_hold_v1_owner_businesses__business_id__clients__client_id__notes__note_id__legal_hold_patch"];
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/clients/{client_id}/sms-consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Sms Consent */
        post: operations["capture_sms_consent_v1_owner_businesses__business_id__clients__client_id__sms_consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/local-time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Local Time */
        get: operations["resolve_local_time_v1_owner_businesses__business_id__local_time_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["get_policy_v1_owner_businesses__business_id__policy_get"];
        /** Edit Policy */
        put: operations["edit_policy_v1_owner_businesses__business_id__policy_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/policy/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed Policy */
        post: operations["seed_policy_v1_owner_businesses__business_id__policy_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending Requests */
        get: operations["pending_requests_v1_owner_businesses__business_id__requests_get"];
        put?: never;
        /** Create Request */
        post: operations["create_request_v1_owner_businesses__business_id__requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/requests/{appointment_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_v1_owner_businesses__business_id__requests__appointment_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/requests/{appointment_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline */
        post: operations["decline_v1_owner_businesses__business_id__requests__appointment_id__decline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/businesses/{business_id}/sms-delivery-failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sms Delivery Failures */
        get: operations["sms_delivery_failures_v1_owner_businesses__business_id__sms_delivery_failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountInvitationBody */
        AccountInvitationBody: {
            /** Email */
            email: string;
        };
        /** BlockBody */
        BlockBody: {
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Expected Revision */
            expected_revision: number;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
        };
        /** ClientNoteBody */
        ClientNoteBody: {
            /** Appointment Id */
            appointment_id?: string | null;
            /** Body */
            body: string;
        };
        /** ClientProfileBody */
        ClientProfileBody: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Default Duration Minutes */
            default_duration_minutes: number;
            /** Expected Version */
            expected_version: number;
            home_size: components["schemas"]["HomeSize"];
            /** Name */
            name: string;
            /** Phone E164 */
            phone_e164: string;
            /** Service Address */
            service_address: string;
        };
        /** ClientSession */
        ClientSession: {
            /** Business Id */
            business_id: string;
            /** Client Id */
            client_id: string;
            /**
             * Role
             * @default client
             */
            role: string;
        };
        /** DecisionBody */
        DecisionBody: {
            /** Expected Version */
            expected_version: number;
        };
        /** EditAppointmentBody */
        EditAppointmentBody: {
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Expected Version */
            expected_version: number;
            /** Start At */
            start_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldBody */
        HoldBody: {
            /** Client Id */
            client_id: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Replaces Appointment Id */
            replaces_appointment_id?: string | null;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
        };
        /**
         * HolidayCalendar
         * @enum {string}
         */
        HolidayCalendar: "US_FEDERAL";
        /**
         * HomeSize
         * @enum {string}
         */
        HomeSize: "small" | "medium" | "large";
        /** InPersonConsentBody */
        InPersonConsentBody: {
            /** Clear Yes */
            clear_yes: boolean;
            /** Participant Name */
            participant_name: string;
            /** Phone E164 */
            phone_e164: string;
            /** Script Version */
            script_version: string;
        };
        /** LegalHoldBody */
        LegalHoldBody: {
            /** Reason */
            reason: string | null;
        };
        /** ManualAppointmentBody */
        ManualAppointmentBody: {
            /** Client Id */
            client_id: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Expected Revision */
            expected_revision: number;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
        };
        /** ManualInvitationBody */
        ManualInvitationBody: {
            /** Cursor */
            cursor?: string | null;
            /** Message */
            message: string;
        };
        /** MoveBlockBody */
        MoveBlockBody: {
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Expected Revision */
            expected_revision: number;
            /** Expected Version */
            expected_version: number;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
        };
        /** OutreachEditBody */
        OutreachEditBody: {
            /** Expected Version */
            expected_version: number;
            settings: components["schemas"]["OutreachSettingsBody"];
        };
        /** OutreachSettingsBody */
        OutreachSettingsBody: {
            /** Enabled */
            enabled: boolean;
            /** Local Time */
            local_time?: string | null;
            /** Lookahead Weeks */
            lookahead_weeks?: number | null;
            /** Message */
            message?: string | null;
            /** Weekday */
            weekday?: number | null;
        };
        /** PolicyBody */
        PolicyBody: {
            /** Booking Horizon Days */
            booking_horizon_days: number;
            /** Closing Buffer Minutes */
            closing_buffer_minutes: number;
            /** Date Exceptions */
            date_exceptions?: {
                [key: string]: components["schemas"]["WindowBody"][];
            };
            /** Hold Minutes */
            hold_minutes: number;
            holiday_calendar?: components["schemas"]["HolidayCalendar"] | null;
            /** Maximum Buffer Minutes */
            maximum_buffer_minutes: number;
            /** Maximum Visit Minutes */
            maximum_visit_minutes: number;
            /** Minimum Visit Gap Minutes */
            minimum_visit_gap_minutes: number;
            /** Opening Buffer Minutes */
            opening_buffer_minutes: number;
            /** Slot Increment Minutes */
            slot_increment_minutes: number;
            /** Timezone */
            timezone: string;
            /** Weekly Windows */
            weekly_windows: {
                [key: string]: components["schemas"]["WindowBody"][];
            };
        };
        /** PolicyEditBody */
        PolicyEditBody: {
            /** Expected Revision */
            expected_revision: number;
            /** Expected Version */
            expected_version: number;
            policy: components["schemas"]["PolicyBody"];
        };
        /** RemoveBlockBody */
        RemoveBlockBody: {
            /** Expected Revision */
            expected_revision: number;
            /** Expected Version */
            expected_version: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WindowBody */
        WindowBody: {
            /**
             * Closes
             * Format: time
             */
            closes: string;
            /**
             * Opens
             * Format: time
             */
            opens: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    activate_client_account_v1_account_invitations__business_id___client_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_session_v1_client_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientSession"];
                };
            };
        };
    };
    create_appointment_v1_owner_businesses__business_id__appointments_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualAppointmentBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_owner_appointment_v1_owner_businesses__business_id__appointments__appointment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_appointment_v1_owner_businesses__business_id__appointments__appointment_id__patch: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditAppointmentBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_v1_owner_businesses__business_id__appointments__appointment_id__cancel_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_block_v1_owner_businesses__business_id__blocks_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_owner_block_v1_owner_businesses__business_id__blocks__block_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_block_v1_owner_businesses__business_id__blocks__block_id__put: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveBlockBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_block_v1_owner_businesses__business_id__blocks__block_id__delete: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveBlockBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_manual_invitations_v1_owner_businesses__business_id__booking_invitations_manual_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_manual_invitations_v1_owner_businesses__business_id__booking_invitations_manual_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualInvitationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_outreach_v1_owner_businesses__business_id__booking_outreach_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_booking_outreach_v1_owner_businesses__business_id__booking_outreach_put: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutreachEditBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    owner_calendar_v1_owner_businesses__business_id__calendar_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_v1_owner_businesses__business_id__clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_v1_owner_businesses__business_id__clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_client_v1_owner_businesses__business_id__clients__client_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientProfileBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    erase_client_v1_owner_businesses__business_id__clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_account_status_v1_owner_businesses__business_id__clients__client_id__account_invitation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_client_account_v1_owner_businesses__business_id__clients__client_id__account_invitation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountInvitationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_client_account_v1_owner_businesses__business_id__clients__client_id__account_invitation_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_client_notes_v1_owner_businesses__business_id__clients__client_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_note_v1_owner_businesses__business_id__clients__client_id__notes_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientNoteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_note_v1_owner_businesses__business_id__clients__client_id__notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                client_id: string;
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_client_note_hold_v1_owner_businesses__business_id__clients__client_id__notes__note_id__legal_hold_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                client_id: string;
                note_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegalHoldBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_sms_consent_v1_owner_businesses__business_id__clients__client_id__sms_consent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InPersonConsentBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_local_time_v1_owner_businesses__business_id__local_time_get: {
        parameters: {
            query: {
                value: string;
            };
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_policy_v1_owner_businesses__business_id__policy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_policy_v1_owner_businesses__business_id__policy_put: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyEditBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_policy_v1_owner_businesses__business_id__policy_seed_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pending_requests_v1_owner_businesses__business_id__requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_v1_owner_businesses__business_id__requests_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_v1_owner_businesses__business_id__requests__appointment_id__approve_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_v1_owner_businesses__business_id__requests__appointment_id__decline_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                business_id: string;
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sms_delivery_failures_v1_owner_businesses__business_id__sms_delivery_failures_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
